//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macellum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fisk
    {
        public int Id { get; set; }
        public string AvgPrice { get; set; }
        public string MaxPrice { get; set; }
        public string Sort { get; set; }
        public string Amount { get; set; }
        public string Dato { get; set; }
        public System.DateTime DatoNew { get; set; }
    
        public virtual Arter Arters { get; set; }
        public virtual Havn Havne { get; set; }
    }
}
