//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macellum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Havn
    {
        public Havn()
        {
            this.Fisk = new HashSet<Fisk>();
        }
    
        public int Id { get; set; }
        public string Navn { get; set; }
    
        public virtual ICollection<Fisk> Fisk { get; set; }
        public virtual BenzinPris BenzinPri { get; set; }
    }
}
